---
- hosts: digitalocean

  tasks:
  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/id_rsa

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=ctf_ssh_key
      ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: ctf_ssh_key

  - name: ensure droplet droplet-ctf-base exists
    digital_ocean: >
      state=present
      command=droplet
      name=droplet-ctf-base
      size_id=512mb
      region_id=sfo2
      image_id=ubuntu-18-04-x64
      ssh_key_ids={{ ctf_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: droplet_ctf_base

  - debug: msg="IP is {{ droplet_ctf_base.droplet.ip_address }}"
